chore: initial setup
tech-university-india/uhi-abdm-adapter pull request #4
Opened 2023-02-21 09:22 UTC by souris-dev

- [X] Express server setup
- [X] Eslint setup
- [X] Jest setup
- [X] Husky pre-push hooks setup (coverage 95% threshold)

Closes issue #1.

2023-02-21 09:43 UTC, rkdixit96 requested changes

2023-02-21 09:43 UTC, rkdixit96 commented on package.json
> +}
Please also configure husky in package.json as shown here - https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/

2023-02-21 10:32 UTC, souris-dev commented on package.json
> +}
Should I go ahead and add lint-staged as well?

2023-02-21 10:38 UTC, souris-dev commented on package.json
> +}
Added husky hooks to package.json, also added lint-staged.

2023-02-22 14:46 UTC, Saatwik-S approved these changes

2023-03-01 07:13 UTC, rkdixit96 approved these changes

2023-03-01 07:14 UTC, merged